title: NLP Notebook
description: NLP Programming Blog
author: Daniel Dorado
logo: /static/img/avatar.png
github: https://github.com/apocope
about: Linguist

baseurl: "www.nlpnotebook.com"
url: "www.nlpnotebook.com"

allowsearch: true

# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1


#share:
#  twitter_username: \#
#  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
