title: NLP Notebook
description: A Programming and NLP Blog
author: Daniel J. Dorado
logo: /static/img/avatar.png
github: https://github.com/apocope
about: Computational Linguist

# baseurl: "www.nlpnotebook.com"
url: "https://github.com/apocop/apocop.github.io"

allowsearch: False

disqus_shortname: nlp-notebook
google_analytics: UA-153415457-1


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
